version: '2'
services:
  db:
    image: mysql:5.7
　ports:
      - '3306:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql　---(1)
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
  web:
      image: php:7.1-apache
      ports:
        - '8080:80'　---(2)
      volumes:
        - ./client:/var/www/html　---(3)
      depends_on:
        - db　---(4)
